import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Monitor, Smartphone, MessageCircle, Send, ShoppingBag, Globe, Puzzle, Share, Workflow } from "lucide-react";
const MobileNavigation = ({ isOpen, onClose, user, isAuthenticated = false, onSignIn, onLogin, onJoin, onSignOut, onLogout, }) => {
    if (!isOpen)
        return null;
    // For backward compatibility
    const handleLogin = onLogin || onSignIn;
    const handleLogout = onLogout || onSignOut;
    const isUserLoggedIn = isAuthenticated || user !== null;
    return (_jsx("div", { className: "md:hidden border-t", children: _jsxs("div", { className: "container py-4 space-y-4", children: [_jsx(Link, { to: "/", className: "block py-2 text-base font-medium", onClick: onClose, children: "Home" }), _jsxs("div", { className: "py-2", children: [_jsx("div", { className: "text-base font-medium mb-2", children: "Apps & Integrations" }), _jsxs("div", { className: "pl-4 space-y-2", children: [_jsxs(Link, { to: "/products/private-ai-api", className: "block py-1 text-sm text-muted-foreground font-medium flex items-center gap-2", onClick: onClose, children: [_jsx(Puzzle, { className: "h-4 w-4" }), " Private AI API"] }), _jsxs(Link, { to: "/products/web-chat", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(Monitor, { className: "h-4 w-4" }), " Web Chat"] }), _jsxs(Link, { to: "/products/mobile-chat", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(Smartphone, { className: "h-4 w-4" }), " Mobile Chat"] }), _jsxs(Link, { to: "/products/whatsapp-chat", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(MessageCircle, { className: "h-4 w-4" }), " WhatsApp Chat"] }), _jsxs(Link, { to: "/products/telegram-chat", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(Send, { className: "h-4 w-4" }), " Telegram Chat"] }), _jsxs(Link, { to: "/products/shopify-chat", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(ShoppingBag, { className: "h-4 w-4" }), " Shopify Chat"] }), _jsxs(Link, { to: "/products/wordpress-chat", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(Globe, { className: "h-4 w-4" }), " WordPress Chat"] }), _jsxs(Link, { to: "/products/integrations/zapier", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(Share, { className: "h-4 w-4" }), " Zapier Integration"] }), _jsxs(Link, { to: "/products/integrations/n8n", className: "block py-1 text-sm text-muted-foreground flex items-center gap-2", onClick: onClose, children: [_jsx(Workflow, { className: "h-4 w-4" }), " n8n Integration"] })] })] }), _jsx(Link, { to: "/plans", className: "block py-2 text-base font-medium", onClick: onClose, children: "Plans" }), _jsx(Link, { to: "/contact", className: "block py-2 text-base font-medium", onClick: onClose, children: "Contact" }), _jsx("div", { className: "pt-4 flex flex-col space-y-2", children: isUserLoggedIn ? (_jsxs(_Fragment, { children: [_jsx(Button, { variant: "outline", asChild: true, children: _jsx(Link, { to: "/dashboard", onClick: onClose, children: "Dashboard" }) }), _jsx(Button, { variant: "destructive", onClick: () => {
                                    if (handleLogout)
                                        handleLogout();
                                    onClose();
                                }, children: "Log Out" })] })) : (_jsxs(_Fragment, { children: [_jsx(Button, { variant: "outline", onClick: handleLogin, children: "Sign In" }), _jsx(Button, { onClick: onJoin, children: "Get Started" })] })) })] }) }));
};
export default MobileNavigation;
