import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { LineChart, BarChart, Activity, TrendingUp } from "lucide-react";
const UsageStatistics = ({ dailyMessages = [120, 230, 310, 290, 350, 420, 480], dailyUsers = [45, 52, 68, 74, 83, 90, 95], dailySessions = [78, 132, 190, 230, 260, 310, 350], growthRate = 23.5, period = "Last 7 days", }) => {
    return (_jsxs(Card, { className: "bg-card", children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(CardTitle, { className: "text-lg font-medium", children: "Usage Statistics" }), _jsx("span", { className: "text-sm text-muted-foreground", children: period })] }) }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(LineChart, { className: "h-4 w-4 text-blue-500" }), _jsx("span", { className: "text-sm font-medium", children: "Daily Messages" })] }), _jsx("span", { className: "text-sm font-medium", children: dailyMessages[dailyMessages.length - 1].toLocaleString() })] }), _jsx("div", { className: "h-2 w-full bg-muted overflow-hidden rounded-full", children: _jsx("div", { className: "h-full bg-blue-500 rounded-full", style: {
                                            width: `${(dailyMessages[dailyMessages.length - 1] / 500) * 100}%`,
                                        } }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Activity, { className: "h-4 w-4 text-green-500" }), _jsx("span", { className: "text-sm font-medium", children: "Active Users" })] }), _jsx("span", { className: "text-sm font-medium", children: dailyUsers[dailyUsers.length - 1].toLocaleString() })] }), _jsx("div", { className: "h-2 w-full bg-muted overflow-hidden rounded-full", children: _jsx("div", { className: "h-full bg-green-500 rounded-full", style: {
                                            width: `${(dailyUsers[dailyUsers.length - 1] / 100) * 100}%`,
                                        } }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(BarChart, { className: "h-4 w-4 text-purple-500" }), _jsx("span", { className: "text-sm font-medium", children: "Total Sessions" })] }), _jsx("span", { className: "text-sm font-medium", children: dailySessions[dailySessions.length - 1].toLocaleString() })] }), _jsx("div", { className: "h-2 w-full bg-muted overflow-hidden rounded-full", children: _jsx("div", { className: "h-full bg-purple-500 rounded-full", style: {
                                            width: `${(dailySessions[dailySessions.length - 1] / 400) * 100}%`,
                                        } }) })] }), _jsxs("div", { className: "flex items-center justify-between pt-2 border-t", children: [_jsx("span", { className: "text-sm font-medium", children: "Growth Rate" }), _jsxs("div", { className: "flex items-center gap-1 text-green-500", children: [_jsx(TrendingUp, { className: "h-4 w-4" }), _jsxs("span", { className: "text-sm font-medium", children: [growthRate, "%"] })] })] })] }) })] }));
};
export default UsageStatistics;
